; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Documents and Settings\Jorge Fernandez\Desktop\Sistemas Operativos I\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial16\SysCore\Kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAXXZ				; kernel_entry
EXTRN	?Exit@@YAXXZ:PROC				; Exit
EXTRN	_main:PROC
EXTRN	?InitializeConstructors@@YAXXZ:PROC		; InitializeConstructors
; Function compile flags: /Ogtpy
; File c:\documents and settings\jorge fernandez\desktop\sistemas operativos i\2016-ii-1272-so1-osdevseries-jorgefer00\tutorial16\syscore\kernel\entry.cpp
_TEXT	SEGMENT
?kernel_entry@@YAXXZ PROC				; kernel_entry

; 15   : 
; 16   : #ifdef ARCH_X86
; 17   : 
; 18   : 	// Set registers for protected mode
; 19   : 	_asm {
; 20   : 		cli

	cli

; 21   : 		mov ax, 10h

	mov	ax, 16					; 00000010H

; 22   : 		mov ds, ax

	mov	ds, ax

; 23   : 		mov es, ax

	mov	es, ax

; 24   : 		mov fs, ax

	mov	fs, ax

; 25   : 		mov gs, ax

	mov	gs, ax

; 26   : 	}
; 27   : #endif //ARCH_X86
; 28   : 
; 29   : 	InitializeConstructors();

	call	?InitializeConstructors@@YAXXZ		; InitializeConstructors

; 30   : 	main ();

	call	_main

; 31   : 	Exit ();

	call	?Exit@@YAXXZ				; Exit

; 35   : 		cli

	cli

; 36   : 		hlt

	hlt

; 32   : 
; 33   : #ifdef ARCH_X86
; 34   : 	_asm {

$LL2@kernel_ent:

; 37   : 	}
; 38   : #endif
; 39   : 
; 40   : 	for (;;);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAXXZ ENDP				; kernel_entry
_TEXT	ENDS
END
